Repository Harshal0902/Rudra, pull requests merged in 2021-06, with the labels that each got.

#58 Resolved extra gap after footer
  English/home.css
  Kannada/home.css
Labels: LGMSOC21, 🟩 Level1

#54 pre-loader added
  assets/Loader.gif
  home.css
  home.html
Labels: LGMSOC21, 🟨 Level2

#63 Updated Home Page Article to clickable
  home.css
  home.html
Labels: LGMSOC21, 🟩 Level1

#64 create the md file for docker
  guides/DOCKER.md
Labels: LGMSOC21, documentation, 🟩 Level1

#69 Added Code of Conduct & License
  CONTRIBUTING.md
  README.md
Labels: LGMSOC21, good first issue, 🟩 Level1

#73 Automatic upgradation of the copyright year for issue #72
  home.html
Labels: LGMSOC21, 🟩 Level1

#76 Replaced "Us" by "Theft".
  English/Public/pages/report.html
Labels: LGMSOC21, 🟩 Level1

#77 Added LGMSOC logo under Open Source Program section
  README.md
Labels: LGMSOC21, good first issue, 🟩 Level1

#79 Replaced img tag with markdow syntax
  README.md
Labels: LGMSOC21, 🟩 Level1

#87 Welcome bot
  .github/config.yml
Labels: LGMSOC21, 🟨 Level2

#86 Update README.md
  README.md
Labels: LGMSOC21, good first issue, 🟩 Level1

#89 Initialized React app
  .gitignore
  .vscode/settings.json
  English/Police/pages/FirearmDetection/package-lock.json
  English/home.html
  home.html
  react_app/.gitignore
  react_app/README.md
  react_app/package-lock.json
  react_app/package.json
  react_app/public/assets/Loader.gif
  react_app/public/assets/police.jpg
  react_app/public/assets/public.jpg
  react_app/public/favicon.ico
  react_app/public/index.html
  react_app/public/logo192.png
  react_app/public/logo512.png
  react_app/public/manifest.json
  react_app/public/robots.txt
  react_app/src/App.css
  react_app/src/App.js
  react_app/src/App.test.js
  react_app/src/Components/Footer.js
  react_app/src/Components/LanguageCard.js
  react_app/src/Components/MouseCard.js
  react_app/src/Components/Progressing.js
  react_app/src/Components/Typewriter.js
  react_app/src/css/EnglishService.css
  react_app/src/css/LanguageCard.css
  react_app/src/history.js
  react_app/src/index.css
  react_app/src/index.js
  react_app/src/logo.svg
  react_app/src/pages/EnglishService.js
  react_app/src/pages/Home.js
  react_app/src/reportWebVitals.js
  react_app/src/setupTests.js
Labels: LGMSOC21, 🟧 Level3

#91 Changed font-style in sign-in and sign-up pages
  English/Police/css/style.css
  English/Public/css/style.css
Labels: LGMSOC21, good first issue, 🟩 Level1

#92 Hover Effect #83
  home.css
  home.html
Labels: LGMSOC21, good first issue, 🟩 Level1

#94 Changes done (#85)
  CONTRIBUTING.md
  English/Police/css/chatbot.css
  English/Police/css/footer.css
  English/Police/css/home.css
  English/Police/css/identify.css
  English/Police/css/notes.css
  English/Police/css/report.css
  English/Police/css/style.css
  English/Public/css/chatbot.css
  English/Public/css/footer.css
  English/Public/css/home.css
  English/Public/css/report.css
  English/Public/css/style.css
  English/footer.css
  English/home.css
  Kannada/Police/css/chatbot.css
  Kannada/Police/css/footer.css
  Kannada/Police/css/home.css
  Kannada/Police/css/identify.css
  Kannada/Police/css/notes.css
  Kannada/Police/css/report.css
  Kannada/Police/css/style.css
  Kannada/Public/css/chatbot.css
  Kannada/Public/css/footer.css
  Kannada/Public/css/home.css
  Kannada/Public/css/report.css
  Kannada/Public/css/style.css
  Kannada/footer.css
  Kannada/home.css
  footer.css
Labels: LGMSOC21, 🟨 Level2

#96 Contact Us #82
  home.css
  home.html
Labels: LGMSOC21, 🟨 Level2

#101 Typos and grammatical errors fixed
  English/home.html
  home.html
Labels: LGMSOC21, 🟩 Level1

#102 added badges with links
  README.md
Labels: LGMSOC21, 🟩 Level1

#103 Rudra Logo #98
  assets/Rudra_logo.png
Labels: LGMSOC21, 🟩 Level1

#106 added show and hide feature in password
  English/Police/index.html
  English/Police/pages/sign-up.html
  English/Public/index.html
  English/Public/js/hide.js
  English/Public/pages/sign-up.html
  Kannada/Police/index.html
  Kannada/Police/pages/sign-up.html
  Kannada/Public/index.html
  Kannada/Public/js/hide.js
  Kannada/Public/pages/sign-up.html
Labels: LGMSOC21, 🟨 Level2

#108 Add new favicon to the site
  404.html
  English/Assets/favicon.ico
  English/Assets/favicon1.ico
  English/favicon.js
  Kannada/Assets/favicon.ico
  Kannada/Assets/favicon1.ico
  Kannada/favicon.js
  aboutus.html
  home.html
Labels: LGMSOC21, 🟩 Level1

#110 Update style of cards when hover
  English/home.css
  Kannada/home.css
Labels: LGMSOC21, 🟨 Level2
