Repository Harshal0902/Rudra, pull requests merged in 2021-07, with the labels that each got.

#116 toggle button
  English/Police/css/chatbot.css
  English/Police/css/home.css
  English/Police/css/identify.css
  English/Police/css/notes.css
  English/Police/css/report.css
  English/Police/js/chatbot.js
  English/Police/js/home.js
  English/Police/js/identify.js
  English/Police/js/notes.js
  English/Police/js/report.js
  English/Police/pages/home.html
  English/Police/pages/identify.html
  English/Police/pages/notes.html
  English/Police/pages/report.html
  English/Public/css/chatbot.css
  English/Public/css/home.css
  English/Public/css/report.css
  English/Public/js/chatbot.js
  English/Public/js/home.js
  English/Public/js/report.js
  English/Public/pages/home.html
  English/Public/pages/report.html
  Kannada/Police/css/chatbot.css
  Kannada/Police/css/home.css
  Kannada/Police/css/identify.css
  Kannada/Police/css/notes.css
  Kannada/Police/css/report.css
  Kannada/Police/js/chatbot.js
  Kannada/Police/js/home.js
  Kannada/Police/js/identify.js
  Kannada/Police/js/notes.js
  Kannada/Police/js/report.js
  Kannada/Police/pages/chatbot.html
  Kannada/Police/pages/home.html
  Kannada/Police/pages/identify.html
  Kannada/Police/pages/notes.html
  Kannada/Police/pages/report.html
  Kannada/Public/css/chatbot.css
  Kannada/Public/css/home.css
  Kannada/Public/css/report.css
  Kannada/Public/js/chatbot.js
  Kannada/Public/js/home.js
  Kannada/Public/js/report.js
  Kannada/Public/pages/chatbot.html
  Kannada/Public/pages/home.html
  Kannada/Public/pages/report.html
Labels: LGMSOC21, 🟧 Level3

#122 Changed icons in police and public changes
  English/Police/pages/home.html
  English/Public/pages/home.html
Labels: LGMSOC21, 🟩 Level1

#123 Feedback Page #97
  assets/feedback-word-and-people-networking-online-cartoon-vector-265550051.jpg
  feedback.html
  home.css
  home.html
Labels: LGMSOC21, 🟨 Level2

#127 made the changes #114
  English/Police/css/chatbot.css
  English/Police/pages/home.html
  English/Public/css/chatbot.css
  English/Public/pages/home.html
Labels: LGMSOC21, 🟩 Level1

#132 Corrected the path to images
  guides/DigitalOcean.md
  guides/DigitalOceanPNGs/RESUME_TECH_WRITER.docx
Labels: LGMSOC21, documentation, good first issue, 🟩 Level1
